version: '2'
services:

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "/etc/letsencrypt/live/giftforme.app/fullchain.pem:/etc/ssl/fullchain.pem"
            - "/etc/letsencrypt/live/giftforme.app/privkey.pem:/etc/ssl/privkey.pem"
            - "./:/var/www/html"
        depends_on:
            - php-fpm

    php-fpm:
        image: cytopia/php-fpm-7.2
        restart: always
        environment:
            - TIMEZONE=Europe/Berlin
            - PHP_XDEBUG_ENABLE=1
            - PHP_XDEBUG_REMOTE_HOST=localhost
            - PHP_XDEBUG_REMOTE_PORT=9000
            - API_URL=nginx-api
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"

    composer:
        image: composer
        volumes:
            - "./:/app"
        command: 'install --ignore-platform-reqs'

